name: Issue Curation

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 10 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  consume:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Run Script
        run: ./scripts/consume.sh

      - name: GIT commit and push docs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "villasv@users.noreply.github.com"
          git add database
          git commit -m "Automatic update of static artifacts" || true
          git push
