name: Issue Curation

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 10 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  consume:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Run Script
        run: ./scripts/consume.sh
