name: Issue Curation

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 10 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  curation:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Run Issues Script
        run: ./scripts/issues.sh
