name: Website Deploy

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 5-23/2,1 * * *"
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all history & all branches

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Build
        run: npm ci && npm run build
        env:
          NEODB_PAT: ${{ secrets.NEODB_PAT }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
